# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=30)),
                ('case_user', models.CharField(max_length=15)),
                ('case_vector', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Enter e-mail address', max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15)),
            ],
        ),
    ]
