# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0003_auto_20170422_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcases',
            name='case_vec_num',
            field=models.IntegerField(choices=[('5', '1 - 10'), ('18', '11 - 25'), ('38', '26 - 50'), ('75', '51 - 100')], default='5'),
        ),
        migrations.AlterField(
            model_name='reportedcases',
            name='case_vector',
            field=models.CharField(choices=[('aedes', 'Aedes Mosquito'), ('rat', 'Rat')], default='aedes', max_length=10),
        ),
    ]
